default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

staging:
  <<: *default
  adapter: postgresql
  host: 127.0.0.1
  database: thinkiny_stage
  username: deployer
  password: deployer
  encoding: unicode
  pool: 5

production:
  <<: *default
  adapter: postgresql
  host: 127.0.0.1
  database: thinkiny
  username: deployer
  password: deployer
  encoding: unicode
  pool: 5
