default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: thinkiny_development
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: thinkiny_test
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  host: 127.0.0.1
  database: thinkiny
  username: deployer
  password: <password>
  encoding: unicode
  pool: 5
